### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fdschmidt93** [nvim-telescope/telescope-file-browser.nvim#3]
This issue will keep users informed of any roadmap, gotchas, breaking changes, and the like.

# Roadmap

The next focus will be on refactoring 

* the entry maker and associated path display
* previewer (maybe with upstream PRs) to facilitate customization

## TODOs (PRs welcome :)

TODOs are not really sorted by priority.

- [ ] A view of multi-selections (cf this [comment](https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/41#issuecomment-1004624979))
- [ ] **Warning**: `Batch Rename` (renaming multi-selections) does not account for links between renamed objects yet (difficult fix). In any case, it should be safe to rename disjoint paths.
- [ ] Better handle moving files/folders to targets in which files/folders already exist, see "skipping" in [fb_actions](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/actions.lua)
- [ ] Being able to toggle `depth` in the file browser as `false` is unlimited depth, could be interesting
- [ ] Maybe allow to set application by extension with which a file is opened
- [ ] Own previewer for making previewer truly customize-able (will happen upstream)

The aforementioned list will be continuously updated.

# Contributions

Any help on the above mentioned issues is greatly appreciated! To get started, familiarize with the code base and [plenary's pathlib](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/path.lua). In fact, I'm very much welcome a main maintainer of the project as my work on telescope core already takes a lot of my time allocated to open source.

**Comment by fdschmidt93** [comment]
Important notice: the `Batch Rename` should be used with paths that have interdependence.

For instance, you select a folder and then a sub-file or sub-folder to rename. Since there is no path resolution right now, this fails for the latter paths as they have become invalid. This is non-trivial to resolve.

Nevertheless, atomically renaming multiple files and folders without interdependence should work fine.

**Comment by fdschmidt93** [comment]
As an update: apart from deprecating the file-browser upstream and maybe cleaning up remappings (in co-op with upstream PR), I'll unfortunately won't have too much time up until end of February as work keeps me preoccupied until end of this year and I'll (hopefully) will be travelling throughout January.

With 0.6 now the basic functionality should be working reasonably well and I'll do my best to attend to the small issues in the meantime, too.

Once more, I'd be very happy to get other people on board to help out with developing the extension :)

**Comment by fdschmidt93** [comment]
The default mapping for going to the parent directory will change some time soon as per popular reddit requests (and `<C-g>/g` are slowish).

Please watch out for #62
